In [1]:
import numpy as np

In [3]:
A = np.array([
    [1, 0],
    [0, 2]
])
A

array([[1, 0],
       [0, 2]])

In [4]:
B = np.array([
    [3, 0],
    [0, 4]
])
B

array([[3, 0],
       [0, 4]])

In [5]:
C = np.array([
    [5, 0],
    [0, 6]
])
C

array([[5, 0],
       [0, 6]])

In [8]:
AB = np.kron(A, B)
AB

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [9]:
ABC = np.kron(AB, C)
ABC

array([[15,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 20,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 24,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 30,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 36,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 40,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 48]])